// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhMxdNvaz7yVGHt9bka68pp95ShLexaFQ',
    appId: '1:307593514246:web:5f4bd173bc18664dd92287',
    messagingSenderId: '307593514246',
    projectId: 'frostmart-6adc9',
    authDomain: 'frostmart-6adc9.firebaseapp.com',
    storageBucket: 'frostmart-6adc9.firebasestorage.app',
    measurementId: 'G-78WR4MMWL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PC12YFG_cZwPq3DuSbbRacGbFpJsEX8',
    appId: '1:307593514246:android:da7e291446b2a7dad92287',
    messagingSenderId: '307593514246',
    projectId: 'frostmart-6adc9',
    storageBucket: 'frostmart-6adc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAck-8FLAdsXezHWXqVntMiAHnYRpusy3E',
    appId: '1:307593514246:ios:fb762bc1aabe17c0d92287',
    messagingSenderId: '307593514246',
    projectId: 'frostmart-6adc9',
    storageBucket: 'frostmart-6adc9.firebasestorage.app',
    iosBundleId: 'com.example.frostMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAck-8FLAdsXezHWXqVntMiAHnYRpusy3E',
    appId: '1:307593514246:ios:fb762bc1aabe17c0d92287',
    messagingSenderId: '307593514246',
    projectId: 'frostmart-6adc9',
    storageBucket: 'frostmart-6adc9.firebasestorage.app',
    iosBundleId: 'com.example.frostMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhMxdNvaz7yVGHt9bka68pp95ShLexaFQ',
    appId: '1:307593514246:web:c3721e671dc2ae2cd92287',
    messagingSenderId: '307593514246',
    projectId: 'frostmart-6adc9',
    authDomain: 'frostmart-6adc9.firebaseapp.com',
    storageBucket: 'frostmart-6adc9.firebasestorage.app',
    measurementId: 'G-EQQ6Y1GRNE',
  );
}
